### ISSUE TITLE
Piccole cose da aggiustare

### ISSUE THREAD

**Issue by Kekko01** [antoniopacillo/fight_covid#1]
Alcune cose da aggiustare secondo me:
lo sparo della siringa un po più a destra (si vede prima che si spari), e la siringa metterla in verticale ( (se vuoi l'ho creato velocemente io al sito https://imgur.com/a/4CZCXG9, però l'immagine è di 15*41 px)

Poi quando c'è un Game Over c'è un errore alla riga 66
`screen.blit(virus_img, (self.army_x[i], self.army_y[i]))`
Il messaggio di errore:

> Warning (from warnings module):
>   File "C:\Users\franc\Documents\GitHub\fight_covid\fight_the_virus.py", line 66
>     screen.blit(virus_img, (self.army_x[i], self.army_y[i]))
> DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
> 
Prova a fare un casting di int.

Poi rallenterei un po' i movimenti del player.

**Comment by antoniopacillo** [comment]
Egregio ezzio greggio la ringrazio vivamente dei consigli

Il ven 6 mar 2020, 4:07 PM Francesco Ciociola <notifications@github.com> ha
scritto:

**Comment by Kekko01** [comment]
Eh di che', è un piacere 😁
